name = "codegen"
version = "0.1.0"
gleam = ">= 1.4.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
verum = { path = "../../verum" }
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
